version: "3.7"

services:
  dev-go-api:
    build:
      context: .
      dockerfile: ./DevDockerfile  
    volumes:
      - ./src:/root/src
    env_file:
      - .env
    ports:
      - 8000:8000
    stdin_open: true
    tty: true