version: "3.7"

services:
  dev-go-api:
    build:
      context: ../
      dockerfile: ./dev/DevDockerfile  
    volumes:
      - ../src:/root/src
      - ../dev/.air.toml:/root/.air.toml
    env_file:
      - ../.env
    ports:
      - 8000:8000
    stdin_open: true
    tty: true